export const PASS_ON_BACK_HOME_SCREEN = 'PASS_ON_BACK_HOME_SCREEN';
export const PASS_ON_BACK_NEW_PRODUCTS_SCREEN = 'PASS_ON_BACK_NEW_PRODUCTS_SCREEN';
export const PASS_ON_BACK_DAILY_OFFERS_SCREEN = 'PASS_ON_BACK_DAILY_OFFERS_SCREEN';
export const NEW_PRODUCTS_COUNT = 'NEW_PRODUCTS_COUNT';
export const NEW_OFFERS_COUNT = 'NEW_OFFERS_COUNT';